modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0"
issueTrackerURL="http://github.com/MoegTech/EnergyLevelTransition/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="gravitation" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Gravitation" #mandatory
updateJSONURL="http://www.teammoeg.com/" #optional
displayURL="http://www.teammoeg.com/" #optional
logoFile="pack.png" #optional
credits="All Contributors" #optional
authors="TeamMoeg" #optional
description='''
    True space.
    '''